builds:
- binary: tviewex
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
  env:
    - CGO_ENABLED=0
  flags:
    - -mod=vendor

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: dayoneops-ai
    name: tviewex
  draft: false
  target_commitish: "{{ .Commit }}"

brews:
  -
    name: tviewex
    repository:
      owner: dayoneops.ai
      name: homebrew-tviewex
    homepage: "https://github.com/dayoneops-ai/homebrew-tviewex"
    description: "Scanner"
    test: |
      system "#{bin}/tviewex", "--version"