builds:
- binary: tviewex
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64
  env:
    - CGO_ENABLED=0
  flags:
    - -mod=vendor

checksum:
  name_template: 'checksums.txt'

brews:
  -
    name: tviewex
    alternative_names:
      - tviewex@{{ .Version }}
      - tviewex@{{ .Major }}
    repository:
      owner: dayoneops-ai
      name: homebrew-tviewex
      token: "${{ secrets.BREW_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/dayoneops-ai/homebrew-tviewex"
    description: "Scanner"
    license: MIT
    test: |
      system "#{bin}/tviewex", "--version"
    dependencies:
      - name: go
        type: optional
    

sboms:
  - artifacts: archive

release:
  github:
    owner: dayoneops-ai
    name: tviewex
  draft: false
  target_commitish: "{{ .Commit }}"
