# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewTviewex < Formula
  desc "Scanner"
  homepage "https://github.com/dayoneops-ai/homebrew-tviewex"
  version "0.24"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dayoneops-ai/homebrew-tviewex/releases/download/v0.24/homebrew-tviewex_0.24_darwin_arm64.tar.gz"
      sha256 "ec03f0429cf88d7dcb885104ace15cb5a05eacad5d2ce8649b2987230bfb160f"

      def install
        bin.install "tviewex"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dayoneops-ai/homebrew-tviewex/releases/download/v0.24/homebrew-tviewex_0.24_darwin_amd64.tar.gz"
      sha256 "92b00f40f9894bea9245757b7f7c894415d36917e9194487979c103acc974774"

      def install
        bin.install "tviewex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dayoneops-ai/homebrew-tviewex/releases/download/v0.24/homebrew-tviewex_0.24_linux_amd64.tar.gz"
      sha256 "d5d49a47ac2c83fb6e7fef3b753179f13696c3726da22c50bf8dc4ea5c370294"

      def install
        bin.install "tviewex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dayoneops-ai/homebrew-tviewex/releases/download/v0.24/homebrew-tviewex_0.24_linux_arm64.tar.gz"
      sha256 "7383db9817a9fd996fb729aa27c3cf0b54841ce5a7492c118760bf8481db1155"

      def install
        bin.install "tviewex"
      end
    end
  end

  test do
    system "#{bin}/tviewex", "--version"
  end
end
