# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tviewex < Formula
  desc "Scanner"
  homepage "https://github.com/dayoneops-ai/homebrew-tviewex"
  version "0.26"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    url "https://github.com/dayoneops-ai/homebrew-tviewex/releases/download/v0.26/homebrew-tviewex_0.26_darwin_amd64.tar.gz", using: CurlDownloadStrategy
    sha256 "1fdaf36ad7853f1fcdafa9f78289c3f15069d6293c493161576b52c1cde509ec"

    def install
      bin.install "tviewex"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Tviewex
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dayoneops-ai/homebrew-tviewex/releases/download/v0.26/homebrew-tviewex_0.26_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "37aa10f7f91e6d921cba0405a6ac5d3700047cc115747377d763edfb25623d7b"

      def install
        bin.install "tviewex"
      end
    end
  end

  test do
    system "#{bin}/tviewex", "--version"
  end
end
